IMAGETYPE_STANDARD  equ   0
IMAGETYPE_NUMBERS   equ   1
IMAGETYPE_BITMAP    equ   2

TILE_ABOVE          equ   0
TILE_BELOW          equ   1
TILE_LEFT           equ   2
TILE_RIGHT          equ   3

EASY                equ  50
EASY_MOVELIMIT		equ	 75
EASY_TIMELIMIT		equ  75
MEDIUM              equ 100
MEDIUM_MOVELIMIT	equ 150
MEDIUM_TIMELIMIT	equ 150
HARD                equ 200
HARD_MOVELIMIT		equ 300
HARD_TIMELIMIT		equ	300

MI_NEWGAME          equ 101
MI_OPENBITMAP       equ 102
MI_DIFFICULTYEASY   equ 103
MI_DIFFICULTYMEDIUM equ 104
MI_DIFFICULTYHARD   equ 105
MI_USESTANDARD      equ 106
MI_USENUMBERS       equ 107
MI_USEFILE          equ 108
MI_COLORRED         equ 109
MI_COLORGREEN       equ 110
MI_COLORBLUE        equ 111
MI_COLORBLACK       equ 112
MI_COLORWHITE       equ 113
MI_HINT             equ 114
MI_MOVELIMITON      equ 115
MI_MOVELIMITOFF     equ 116
MI_TIMELIMITON      equ 117
MI_TIMELIMITOFF     equ 118
MI_HELP             equ 119
MI_ABOUT            equ 120

ID_TIMER1           equ 220

MAINMENU            equ 301

ICON1_BIG           equ 400
ICON2_SMALL         equ 401

CID_STATUS          equ 600
CID_STATIC          equ 601
CID_TOOLBAR         equ 602

ID_ABOUTDIALOG      equ 700
ID_SETTINGSDIALOG   equ 701

BMP_TOOLBAR         equ 801
BMP_STARTBITMAP     equ 802

IDD_PREVIEWDIALOG   equ 1100
